# Generated by Django 4.2.4 on 2023-09-02 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_description', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('product_price', models.CharField(default='', max_length=500, null=True)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing_men', 'Men’s Clothing'), ('clothing_women', 'Women’s Clothing'), ('clothing_children', 'Children’s Clothing'), ('food', 'Food'), ('toys', 'Toys'), ('books', 'Books'), ('furniture', 'Furniture'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('automotive', 'Automotive'), ('home_garden', 'Home & Garden'), ('office_supplies', 'Office Supplies'), ('musical_instruments', 'Musical Instruments'), ('pet_supplies', 'Pet Supplies'), ('jewelry', 'Jewelry'), ('art_crafts', 'Arts & Crafts'), ('health', 'Health & Household'), ('computers', 'Computers & Accessories'), ('shoes', 'Shoes'), ('bags', 'Handbags & Wallets'), ('watches', 'Watches'), ('baby', 'Baby Products'), ('kitchen', 'Kitchen & Dining'), ('tools', 'Tools & Home Improvement'), ('video_games', 'Video Games'), ('groceries', 'Grocery & Gourmet Food'), ('industrial', 'Industrial & Scientific'), ('movies_tv', 'Movies & TV'), ('digital_music', 'Digital Music'), ('toiletries', 'Toiletries'), ('appliances', 'Appliances'), ('smart_home', 'Smart Home'), ('travel', 'Travel Gear'), ('cameras', 'Cameras & Photography'), ('collectibles', 'Collectibles & Fine Art'), ('software', 'Software'), ('cellphones', 'Cell Phones & Accessories'), ('audio', 'Audio & Home Theatre'), ('pharmacy', 'Pharmacy'), ('musical_equipment', 'DJ, Electronic Music & Karaoke'), ('magazines', 'Magazines'), ('gift_cards', 'Gift Cards'), ('wine', 'Wine'), ('farming', 'Farming & Agricultural'), ('outdoor_recreation', 'Outdoor Recreation'), ('home_decor', 'Home Décor'), ('bed_bath', 'Bed & Bath'), ('stationery', 'Stationery & Gift Wrapping'), ('hobbies', 'Hobbies'), ('motorcycles', 'Motorcycles & Powersports'), ('vintage_antiques', 'Vintage & Antiques'), ('subscriptions', 'Subscription Services'), ('education', 'Educational Supplies'), ('garden_tools', 'Gardening Tools'), ('luxury_brands', 'Luxury Brands'), ('renewable_energy', 'Renewable Energy'), ('vehicles', 'Vehicles')], default='electronics', max_length=50)),
                ('product_link', models.CharField(default='', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, upload_to='static')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('profile_bio', models.CharField(blank=True, max_length=100, null=True)),
                ('website_link', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedIn_link', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_products', through='WebApp.ProductFavorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_conversations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
