# Generated by Django 4.2.4 on 2023-09-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing_men', 'Men’s Clothing'), ('clothing_women', 'Women’s Clothing'), ('clothing_children', 'Children’s Clothing'), ('food', 'Food'), ('toys', 'Toys'), ('books', 'Books'), ('furniture', 'Furniture'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('automotive', 'Automotive'), ('home_garden', 'Home & Garden'), ('office_supplies', 'Office Supplies'), ('musical_instruments', 'Musical Instruments'), ('pet_supplies', 'Pet Supplies'), ('jewelry', 'Jewelry'), ('art_crafts', 'Arts & Crafts'), ('health', 'Health & Household'), ('computers', 'Computers & Accessories'), ('shoes', 'Shoes'), ('bags', 'Handbags & Wallets'), ('watches', 'Watches'), ('baby', 'Baby Products'), ('kitchen', 'Kitchen & Dining'), ('tools', 'Tools & Home Improvement'), ('video_games', 'Video Games'), ('industrial', 'Industrial & Scientific'), ('movies_tv', 'Movies & TV'), ('digital_music', 'Digital Music'), ('toiletries', 'Toiletries'), ('appliances', 'Appliances'), ('smart_home', 'Smart Home'), ('travel', 'Travel Gear'), ('cameras', 'Cameras & Photography'), ('collectibles', 'Collectibles & Fine Art'), ('software', 'Software'), ('cellphones', 'Cell Phones & Accessories'), ('audio', 'Audio & Home Theatre'), ('pharmacy', 'Pharmacy'), ('musical_equipment', 'DJ, Electronic Music & Karaoke'), ('magazines', 'Magazines'), ('gift_cards', 'Gift Cards'), ('wine', 'Wine'), ('farming', 'Farming & Agricultural'), ('outdoor_recreation', 'Outdoor Recreation'), ('home_decor', 'Home Décor'), ('bed_bath', 'Bed & Bath'), ('stationery', 'Stationery & Gift Wrapping'), ('hobbies', 'Hobbies'), ('motorcycles', 'Motorcycles & Powersports'), ('vintage_antiques', 'Vintage & Antiques'), ('education', 'Educational Supplies'), ('garden_tools', 'Gardening Tools'), ('luxury_brands', 'Luxury Brands'), ('comics', 'Comic Books'), ('graphic_novel', 'Graphic Novel'), ('renewable_energy', 'Renewable Energy'), ('vehicles', 'Vehicles')], default='electronics', max_length=50),
        ),
    ]
